name = "ACreate"
author = "Buzzy"
version = "0.03"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2c5e91b747c49290037be142261e65c55512188a4d43afa261deae33e97bb5e"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
