name = "fuckingvanilla"
author = "me"
version = "no"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "beaf488a7741528c48f4e0b1885d1ffa37f2d08a09d9970517c39fb37c7e26f0"

[versions]
fabric = "0.18.0"
minecraft = "1.21.10"
