name = "ACreate"
author = "Buzzy"
version = "0.03"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a713eb0f19110c5a9d3b093fe643bbd4f5b28f8431c18124a92a7e76909d211"

[versions]
neoforge = "47.1.106"
minecraft = "1.20.1"
