name = "ACreate"
author = "Buzzy"
version = "0.03"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4704d72423e08a98bbdaccabedb6fbf0258a67350a3b0829f74ceb888c5e19fb"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
