name = "ACreate"
author = "Buzzy"
version = "0.03"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b597e565b8e8fac4f869dd0471772106aeb6d38f018fb1a877c1bfda690ed351"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
