name = "fuckingvanilla"
author = "me"
version = "no"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40fe1b9efd1b7edc46e7f316ab9e1b00da67d88857e255524831f9a59fb5b0ff"

[versions]
fabric = "0.18.0"
minecraft = "1.21.10"
