name = "ACreate"
author = "Buzzy"
version = "0.03"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6de80182fbd7f88efda4405a77c443f2c90468aa9c392e7cbe87934aa8e9a404"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
