name = "ACreate"
author = "Buzzy"
version = "0.03"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d8c412b51f2b11f87eb91b68696b0fad15897cf85fd7459e773755d7ac36b10"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
