name = "fuckingvanilla"
author = "me"
version = "no"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb3bd40860289678ac480d685704a9f2ab7279e052545cac8fec91d239951fe5"

[versions]
fabric = "0.18.0"
minecraft = "1.21.10"
