#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Sat Nov 08 22:54:28 EST 2025
alwaysLogTamperWarnings=false
